---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites (Debian/Ubuntu)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      when: ansible_pkg_mgr == 'apt'

    - name: Install pip3 (Debian/Ubuntu)
      package:
        name: python3-pip
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker GPG key (Debian/Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker repository (Debian/Ubuntu)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install Docker (Debian/Ubuntu)
      package:
        name: docker-ce
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Docker Compose (Debian/Ubuntu)
      pip:
        name: docker-compose
        state: present
        executable: pip3
      when: ansible_pkg_mgr == 'apt'

    - name: Install prerequisites (CentOS/RedHat)
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python3
        - python3-pip
      when: ansible_pkg_mgr == 'yum'

    - name: Add Docker repository (CentOS/RedHat)
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_pkg_mgr == 'yum'

    - name: Install Docker (CentOS/RedHat)
      package:
        name: docker-ce
        state: present
      when: ansible_pkg_mgr == 'yum'

    - name: Install Docker Compose (CentOS/RedHat)
      pip:
        name: docker-compose
        state: present
        executable: pip3
      when: ansible_pkg_mgr == 'yum'
