---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisite packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Print Ubuntu distribution release
      debug:
        msg: "Ubuntu release is {{ ansible_distribution_release }}"
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Update APT package index
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Verify Docker repository
      command: apt-cache policy docker-ce
      register: docker_repo_check
      when: ansible_pkg_mgr == 'apt'

    - name: Print Docker repository check
      debug:
        var: docker_repo_check
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker YUM repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
      when: ansible_pkg_mgr == 'yum'

    - name: Install Docker
      package:
        name: docker-ce
        state: present
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

    - name: Install Docker CLI and Rootless extras (if apt is used)
      package:
        name: 
          - docker-ce-cli
          - docker-ce-rootless-extras
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Start Docker service
      service:
        name: docker
        state: started
