- name: Configure single VM
  hosts: cloudinit
  become: true
  vars:
    timezone: "Europe/Amsterdam"

  tasks:
    become: true
    - name: Configure static IP address
      copy:
        dest: /etc/netplan/50-cloud-init.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              {{ interface_name }}:
                dhcp4: no
                addresses:
                  - "{{ static_ip }}"
                gateway4: "{{ gateway }}"
                nameservers:
                  addresses: 
                    - "{{ dns_servers[0] }}"
                    - "{{ dns_servers[1] }}"

    - name: Apply networking changes
      command: netplan apply

    - name: Restart the network interface
      systemd:
        name: systemd-networkd
        state: restarted
        enabled: yes

    - name: Reboot the server to apply network changes
      reboot:
        msg: "Reboot initiated by Ansible for finalizing network and hostname changes."
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Set the hostname after reboot
      command: hostnamectl set-hostname "{{ hostname }}"
      run_once: true
      delegate_to: ad.hydralab.nl

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ static_ip }} {{ hostname }}"
        create: yes

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Ensure SSH service is enabled and running
      systemd:
        name: ssh
        state: started
        enabled: yes

    - name: Install UFW firewall
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
