---
- name: Configure single VM
  hosts: cloudinit
  become: true
  vars:
    timezone: "Europe/Amsterdam"

  tasks:
    - name: Set the hostname using command module
      command: hostnamectl set-hostname "{{ hostname }}"

    - name: Configure static IP address
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              {{ interface_name }}:
                dhcp4: no
                addresses:
                  - "{{ static_ip }}"
                gateway4: "{{ gateway }}"
                nameservers:
                  addresses: 
                    - "{{ dns_servers[0] }}"
                    - "{{ dns_servers[1] }}"

    - name: Apply networking changes
      command: netplan apply

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ static_ip }} {{ hostname }}"
        create: yes

    - name: Restart the network interface
      systemd:
        name: systemd-networkd
        state: restarted
        enabled: yes

    - name: Ensure SSH service is enabled and running
      systemd:
        name: ssh
        state: started
        enabled: yes

    - name: Install UFW firewall
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Reboot the server to apply all changes
      reboot:
        msg: "Reboot initiated by Ansible for finalizing network and hostname changes."
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami


#static config file:
#[cloudinit]
#192.168.1.100 ansible_user=your_ssh_user

#[cloudinit:vars]
#ansible_become=true
#static_ip=192.168.1.100/24
#gateway=192.168.1.1
#dns_servers='["8.8.8.8", "8.8.4.4"]'
#hostname=my-vm-hostname
#interface_name=eth0
